In [7]:
import pandas as pd
import numpy as np
from covid import utils

paths = utils.create_named_tuple('filepaths.txt')
config = utils.create_named_tuple(paths.config)
labels = utils.generate_labels_from_bins(config.age_bins)
bins = config.age_bins
population = pd.read_csv('data/temp_pop.csv')

In [2]:
population

region_id        region    0-6   7-15  16-20   21-40   41-66    67+  \
0          301          OSLO  55837  64036  33296  257985  207877  77749   
1         1101     EIGERSUND   1132   1719    955    3642    4898   2439   
2         1103     STAVANGER  11735  16218   8511   41917   47283  18451   
3         1106     HAUGESUND   2636   3996   2314    9836   12823   5707   
4         1108       SANDNES   7589  10110   5042   22845   25653   9206   
..         ...           ...    ...    ...    ...     ...     ...    ...   
351       5440      BERLEVÅG     47     61     46     219     341    214   
352       5441          TANA    166    232    154     624    1052    600   
353       5442       NESSEBY     33     86     40     197     295    229   
354       5443     BÅTSFJORD    150    197    124     622     761    346   
355       5444  SØR-VARANGER    639    967    627    2707    3499   1662   

     population  
0        696780  
1         14785  
2        144115  
3         37312  
4         80445  
..          ...  
351         928  
352        2828  
353         880  
354        2200  
355       10101  

[356 rows x 9 columns]

In [96]:
df = pd.read_csv('data/contact_data.csv')
df.contact_age_0 = pd.cut(df['contact_age_0'], bins=bins+[110], labels=labels, include_lowest=True)
df.contact_age_1 = pd.cut(df['contact_age_1'], bins=bins+[110], labels=labels, include_lowest=True)
df_mat = pd.DataFrame(df[df.columns[:-2]].groupby(['contact_age_0', 'contact_age_1']).mean()).reset_index()
N = population[population.columns[2:-1]].sum().to_numpy()
matrices = []
for col in ['home', 'work', 'school', 'transport', 'leisure']:
    matrix = pd.pivot_table(df_mat, values=col, index='contact_age_0', columns='contact_age_1').to_numpy()
    for i in range(len(labels)):
        for j in range(len(labels)):
            matrix[i][j] = 1/(2*N_norway[i]) * (matrix[i][j] * N_norway[i] + matrix[j][i] * N_norway[j])
    matrices.append(matrix)

In [99]:
print(matrices[0])

[[0.17757595 0.57297936 0.40674975 1.26469302 1.18443428 0.8278129 ]
 [0.42578024 0.10825177 0.23417074 0.76736307 0.96007033 0.70418178]
 [0.54072403 0.34647748 0.08262404 0.55450634 1.53849391 0.75160783]
 [0.44969302 0.36695059 0.15761289 0.17806604 0.23624923 0.26712678]
 [0.35349246 0.39288113 0.37736357 0.20249664 0.23427123 0.24058188]
 [0.42425219 0.48866042 0.3420947  0.38397074 0.40016794 0.4047619 ]]


In [83]:
matrix = pd.pivot_table(df_mat, values='school', index='contact_age_0', columns='contact_age_1').to_numpy()
print(matrix)

[[0.61885374 0.18974359 0.09333333 0.11187215 0.27794562 0.        ]
 [0.21635012 0.68612892 0.29847716 0.14990512 0.21806054 0.04929577]
 [0.09917355 0.356623   0.57733029 0.08689356 0.1888563  0.00952381]
 [0.14445452 0.23681125 0.17854114 0.07002903 0.02604744 0.00768049]
 [0.1242485  0.22863248 0.17163789 0.02914932 0.02490388 0.00929054]
 [0.02535211 0.02066116 0.01129944 0.01534829 0.00742942 0.0070028 ]]


In [90]:
for i in range(len(labels)):
    for j in range(len(labels)):
        matrix[i][j] = 1/(2*N_norway[i]) * (matrix[i][j] * N_norway[i] + matrix[j][i] * N_norway[j])
print(matrix)

[[0.61885374 0.24987827 0.08580531 0.31448522 0.4134231  0.0265667 ]
 [0.1953669  0.68612892 0.24745781 0.37074811 0.46147238 0.03975757]
 [0.10394238 0.40293437 0.57733029 0.44831193 0.57476492 0.0197636 ]
 [0.11615393 0.19261003 0.13869574 0.07002903 0.03101073 0.0083333 ]
 [0.10891523 0.1891566  0.13716388 0.02713847 0.02490388 0.00640755]
 [0.01901408 0.02392182 0.00937126 0.01479079 0.01046794 0.0070028 ]]


In [ ]:
matrix = pd.pivot_table(df_mat, values='school', index='contact_age_0', columns='contact_age_1')
matrix += matrix.T
matrix.values[tuple([np.arange(matrix.shape[0])]*2)] = matrix.values[tuple([np.arange(matrix.shape[0])]*2)]/2
matrix = np.array([[np.round(matrix[i][j]/(age_pop[i]+age_pop[j]),2) for i in labels] for j in labels])

In [63]:
print(scaling_factors)

[[1.         0.80969661 0.83141599 1.07162259 1.19204809 2.85870673]
 [1.30724163 1.         1.03506558 1.42287511 1.61730006 4.30809255]
 [1.25433897 0.96723245 1.         1.3623944  1.54407768 4.05852882]
 [0.9373515  0.77089256 0.78989057 1.         1.10533654 2.56316786]
 [0.86124657 0.72375368 0.73944578 0.91299341 1.         2.20414945]
 [0.60599029 0.56564966 0.57025375 0.62117288 0.64670075 1.        ]]


In [18]:
matrix

array([[0.12, 0.01, 0.  , 0.02, 0.01, 0.  ],
       [0.01, 0.21, 0.03, 0.02, 0.03, 0.  ],
       [0.  , 0.03, 0.14, 0.01, 0.02, 0.  ],
       [0.02, 0.02, 0.01, 0.01, 0.01, 0.  ],
       [0.01, 0.03, 0.02, 0.01, 0.01, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [16]:
df_mat

contact_age_0 contact_age_1  home  work  school  transport  leisure
0            0-6           0-6   567     2    1976        144      790
1            0-6          7-15   389     1     148         62      272
2            0-6         16-20    55    31      14          4       53
3            0-6         21-40   755   193     147        103      336
4            0-6         41-66   427   131     276         40      227
5            0-6           67+    55     1       0          1       27
6           7-15           0-6   547     2     262         82      454
7           7-15          7-15  1283    32    8132        793     2935
8           7-15         16-20   316    21     294         93      358
9           7-15         21-40   741   308     237         94      417
10          7-15         41-66   892   372     425        126      436
11          7-15           67+    97     2       7          2       45
12         16-20           0-6   137     0      24         21       80
13         16-20          7-15   368     6     490        112      530
14         16-20         16-20   398   136    2781        387     1608
15         16-20         21-40   323   441     120         71      532
16         16-20         41-66   667   358     322         92      392
17         16-20           67+    46     6       1          2       54
18         21-40           0-6  1807    16     478        251     1196
19         21-40          7-15  1456    17     808        235     1168
20         21-40         16-20   455   270     421        160     1144
21         21-40         21-40  1963  4035     772        524     4386
22         21-40         41-66  1885  3363     235        366     3518
23         21-40           67+   229    56       5         20      371
24         41-66           0-6   876    24     248        114      910
25         41-66          7-15  1554    15     749        216      992
26         41-66         16-20   917   176     328        129      475
27         41-66         21-40  1436  2862     196        286     2208
28         41-66         41-66  2681  4061     285        525     4435
29         41-66           67+   405    53      11         43      719
30           67+           0-6   161     1       9         12      194
31           67+          7-15   240     2      10         28      224
32           67+         16-20    71    25       2          6       80
33           67+         21-40   264   220      13         24      348
34           67+         41-66   592   378      15         76     1036
35           67+           67+   289    15       5         19      420

In [19]:
age_pop

0-6       8407.0
7-15     19449.0
16-20    10011.0
21-40    26323.5
41-66    26833.5
67+       3735.0
dtype: float64