In [154]:
import pandas as pd
import numpy as np
def generate_custom_population(bins, labels):
    total_pop = pd.read_csv('data/municipalities/age_divided_population.csv')
    age_divided = pd.DataFrame(total_pop.groupby(['region_id', pd.cut(pop["age"], bins=bins+[110], labels=labels, include_lowest=True)]).sum('population')['population'])
    age_divided.reset_index(inplace=True)
    age_divided = age_divided.pivot(index='region_id', columns=['age'])['population']
    region_names_id = pd.read_csv("data/municipalities/Kommunenummer_navn_2020.csv", delimiter=",").drop_duplicates()
    df = pd.merge(region_names_id, age_divided, on="region_id", how='right', sort=True)
    df['population'] = df.loc[:,df.columns[2:2+len(labels)]].sum(axis=1)
    return df

def generate_labels_from_bins(bins):
    labels = []
    for i in range(len(bins)-1):
        if i == 0:
            labels.append(str(bins[i])+"-"+str(bins[i+1]))
        else:
            labels.append(str(bins[i]+1)+"-"+str(bins[i+1]))
    labels.append(str(bins[-1]+1)+"+")
    return labels

bins = [0,5,15,19,66]
df = generate_custom_population(bins, generate_labels_from_bins(bins))
df

region_id        region    0-5   6-15  16-19   20-66    67+  population
0          301          OSLO  48242  71631  25672  473486  77749      696780
1         1101     EIGERSUND    957   1894    739    8756   2439       14785
2         1103     STAVANGER  10034  17919   6740   90971  18451      144115
3         1106     HAUGESUND   2252   4380   1831   23142   5707       37312
4         1108       SANDNES   6462  11237   4057   49483   9206       80445
..         ...           ...    ...    ...    ...     ...    ...         ...
351       5440      BERLEVÅG     43     65     42     564    214         928
352       5441          TANA    142    256    115    1715    600        2828
353       5442       NESSEBY     26     93     31     501    229         880
354       5443     BÅTSFJORD    133    214     97    1410    346        2200
355       5444  SØR-VARANGER    544   1062    495    6338   1662       10101

[356 rows x 8 columns]

In [160]:
available_vaccines = 1000
pop_weight = df[df.columns[2:-1]].to_numpy()/df.population.sum()
decision = available_vaccines * pop_weight
decision

array([[8.95011390e+00, 1.32893663e+01, 4.76280677e+00, 8.78436556e+01,
        1.44244104e+01],
       [1.77547759e-01, 3.51385012e-01, 1.37103233e-01, 1.62445996e+00,
        4.52496327e-01],
       [1.86156136e+00, 3.32442873e+00, 1.25044085e+00, 1.68774266e+01,
        3.42312822e+00],
       ...,
       [4.82365908e-03, 1.72538575e-02, 5.75128583e-03, 9.29482000e-02,
        4.24853050e-02],
       [2.46748715e-02, 3.97024248e-02, 1.79959589e-02, 2.61590743e-01,
        6.41917709e-02],
       [1.00925790e-01, 1.97027921e-01, 9.18350479e-02, 1.17585966e+00,
        3.08343131e-01]])

In [80]:
c = np.array([[[0.005, 0.02, 0.01, 0.02, 0.08, 0.04, 0.01],
    [0.02,  0.05, 0.04, 0.03, 0.2,  0.1,  0.05],
    [0.01,  0.04, 0.04, 0.02, 0.1,  0.1,  0.05],
    [0.02,  0.03, 0.02, 0.02, 0.1,  0.09, 0.03],
    [0.08,  0.2,  0.1,  0.1,  0.5,  0.4,  0.2 ],
    [0.04,  0.1,  0.1,  0.09, 0.4,  0.3,  0.1 ],
    [0.01,  0.05, 0.05, 0.03, 0.2,  0.1,  0.1 ]],
    [[0.4,   0,    0,     0,   0,    0,    0],
    [0,     0.9,  0.09,  0,   0,    0,    0],
    [0,     0.09, 0.5,   0,   0,    0,    0],
    [0,     0,    0,     1,   0,    0,    0],
    [0,     0,    0,     0,   0,    0,    0],
    [0,     0,    0,     0,   0,    0,    0],
    [0,     0,    0,     0,   0,    0,    0]],
    [[0,     0,    0,     0,   0,    0,    0],
    [0,     0,    0,     0,   0,    0,    0],
    [0,     0,    0.1,   0.2, 0.2,  0.06, 0],
    [0,     0,    0.2,   0.4, 0.4,  0.1,  0],
    [0,     0,    0.2,   0.4, 0.5,  0.1,  0],
    [0,     0,    0.06,  0.1, 0.1,  0.03, 0],
    [0,     0,    0,     0,   0,    0,    0]],
    [[0.06,  0.08, 0.1,   0.1,  0.1,  0.1,  0.03],
    [0.08,  0.1,  0.1,   0.1,  0.2,  0.1,  0.04],
    [0.1,   0.1,  0.2,   0.2,  0.2,  0.2,  0.05],
    [0.1,   0.1,  0.2,   0.2,  0.2,  0.2,  0.05],
    [0.1,   0.2,  0.2,   0.2,  0.3,  0.2,  0.07],
    [0.1,   0.1,  0.2,   0.2,  0.2,  0.2,  0.05],
    [0.03,  0.04, 0.05,  0.05, 0.07, 0.05, 0.01]]])

In [81]:
temp = np.zeros(shape=(4,7,7))
for i, mat in enumerate(c):
    for j, row in enumerate(mat):
        for k, col in enumerate(row):
            if k == 2 or k == 4:
                temp[i][j][k] = (c[i][j][k] + c[i][j][k+1]) / 2
            elif j == 2 or j == 4:
                temp[i][j][k] = (c[i][j][k] + c[i][j+1][k]) / 2
            else:
                temp[i][j][k] = col
final = []
for mat in temp:
    t_mat = np.delete(mat, 5, 0)
    t_mat = np.delete(t_mat, 5, 1)
    t_mat = np.delete(t_mat, 3, 0)
    t_mat = np.delete(t_mat, 3, 1)
    final.append(t_mat)

In [85]:
final

[array([[0.005, 0.02 , 0.015, 0.06 , 0.01 ],
        [0.02 , 0.05 , 0.035, 0.15 , 0.05 ],
        [0.015, 0.035, 0.03 , 0.1  , 0.04 ],
        [0.06 , 0.15 , 0.1  , 0.45 , 0.15 ],
        [0.01 , 0.05 , 0.04 , 0.15 , 0.1  ]]),
 array([[0.4  , 0.   , 0.   , 0.   , 0.   ],
        [0.   , 0.9  , 0.045, 0.   , 0.   ],
        [0.   , 0.045, 0.25 , 0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , 0.   , 0.   ]]),
 array([[0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  ],
        [0.  , 0.  , 0.15, 0.13, 0.  ],
        [0.  , 0.  , 0.3 , 0.3 , 0.  ],
        [0.  , 0.  , 0.  , 0.  , 0.  ]]),
 array([[0.06, 0.08, 0.1 , 0.1 , 0.03],
        [0.08, 0.1 , 0.1 , 0.15, 0.04],
        [0.1 , 0.1 , 0.2 , 0.2 , 0.05],
        [0.1 , 0.15, 0.2 , 0.25, 0.06],
        [0.03, 0.04, 0.05, 0.06, 0.01]])]