In [33]:
from covid import utils
import numpy as np
import pandas as pd

In [71]:
individuals_path =  "/Users/sandernordeide/Epidemiologic-Vaccine-Strategies/results/GA_20210508171405/individuals/individuals_0.pkl"
score_path =        "/Users/sandernordeide/Epidemiologic-Vaccine-Strategies/results/GA_20210508171405/final_scores/final_score_0.pkl"
overview_path =     "/Users/sandernordeide/Epidemiologic-Vaccine-Strategies/results/GA_20210508171405/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [72]:
for ID in final_score.keys():
    print(np.mean(final_score[ID]))

5532.106066670124
4574.034875684036


In [73]:
overview.sort_values('mean_score')

generation       individual   mean_score
0           0  140732027070928  4574.034876
1           0  140732027071264  5532.106067

In [83]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Strategy count: {i.strategy_count['D']}")
    print(f"Score: {i.mean_score}")
    print(f"Genes\n{i.genes}")
    print()

ID: 140732027070928
Strategy count: defaultdict(<class 'int'>, {'1': 10, '2': 10, '3': 9, '4': 9, 0: 0})
Score: 4574.034875684036
Genes
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]]

ID: 140732027071264
Strategy count: defaultdict(<class 'int'>, {'1': 10, '2': 10, '3': 9, '4': 9, 0: 0})
Score: 5532.106066670124
Genes
[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]]



In [10]:
ind1.genes

array([[[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.]]])

In [11]:
ind2.genes

array([[[0.5, 0.5, 0. , 0. ],
        [0. , 0.5, 0. , 0.5],
        [0. , 1. , 0. , 0. ],
        [0. , 1. , 0. , 0. ]],

       [[0. , 0. , 1. , 0. ],
        [0. , 1. , 0. , 0. ],
        [0. , 1. , 0. , 0. ],
        [0. , 1. , 0. , 0. ]],

       [[0. , 1. , 0. , 0. ],
        [1. , 0. , 0. , 0. ],
        [1. , 0. , 0. , 0. ],
        [0. , 1. , 0. , 0. ]]])