In [2]:
import os
import utils
import numpy as np
import pandas as pd

In [3]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        last_gen = sorted(map(lambda x: x.split("_"), 
                        os.listdir(f"{path}/individuals/")), 
                        key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
        print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
        last_gens.append(int(last_gen))
    return paths, last_gens

In [11]:
dir_path = "results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_27_22_09_14, last generation: 2


In [18]:
run = 0
gen = 5
path = dir_path + paths[run]

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [19]:
with open(dir_path + paths[run] + "/run_params.json", "r") as file:
    print(file.read())
    file.close()

{
    "objective": "deaths",
    "simulations": 5,
    "process": {
        "horizon": 74,
        "decision_period": 28,
        "policy": "weighted"
    },
    "population_size": 5,
    "random_individuals": false,
    "min_generations": 0
}


In [20]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {np.round(i.mean_score, 3)}")
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

1st place:
ID: gen_0_003
Score: 3569.328
Genes:
[[[0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0.]]]

2nd place:
ID: gen_5_004
Score: 3571.987
Genes:
[[[0.    0.    0.    0.985 0.015]
  [0.    0.    0.011 0.989 0.   ]
  [0.    0.    0.004 0.996 0.   ]]

 [[0.    0.    0.049 0.951 0.   ]
  [0.    0.    0.016 0.984 0.   ]
  [0.    0.015 0.015 0.971 0.   ]]

 [[0.016 0.    0.048 0.937 0.   ]
  [0.    0.    0.    1.    0.   ]
  [0.    0.    0.016 0.984 0.   ]]]

3rd place:
ID: gen_2_004
Score: 3576.062
Genes:
[[[0.    0.    0.    1.    0.   ]
  [0.    0.    0.062 0.938 0.   ]
  [0.    0.    0.062 0.938 0.   ]]

 [[0.    0.    0.062 0.938 0.   ]
  [0.    0.    0.062 0.938 0.   ]
  [0.    0.059 0.059 0.882 0.   ]]

 [[0.    0.    0.062 0.938 0.   ]
  [0.    0.    0.062 0.938 0.   ]
  [0.    0.    0.062 0.938 0.   ]]]

4th place:
ID: gen_4_012
Score: 3578.167
Genes:
[[[0

In [30]:
print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.02772154 0.12981317 0.46594438 0.02156354 0.06452118 0.2904362 ]
  [0.45667618 0.         0.         0.12511083 0.         0.41821299]
  [0.         0.         0.99358962 0.         0.         0.00641038]]

 [[0.         0.         0.83418633 0.         0.         0.16581367]
  [0.23311384 0.2417248  0.31167746 0.         0.02920702 0.18427689]
  [0.01268598 0.         0.86100509 0.03305378 0.04611612 0.04713902]]

 [[0.14493941 0.43808816 0.27745665 0.         0.         0.13951578]
  [0.25355091 0.08738514 0.08570492 0.25355091 0.0047617  0.31504641]
  [0.01869097 0.15650874 0.20236493 0.0408563  0.5704409  0.01113814]]]

[0.12748654 0.11705778 0.44799215 0.05268171 0.07944966 0.17533217]
