In [1]:
from covid import utils
import numpy as np
import pandas as pd

In [8]:
path = "results/GA_20210509190222"
gen = 3

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [9]:
overview.sort_values('mean_score')

generation individual   mean_score
63           3  gen_3_001  7186.755472
64           3  gen_2_001  7201.671233
65           3  gen_0_008  7208.863852
66           3  gen_0_004  7213.270707
67           3  gen_1_003  7215.220536
..         ...        ...          ...
58           2  gen_0_013  7577.481384
59           2  gen_0_001  7591.126109
60           2  gen_0_011  7593.266462
61           2  gen_0_014  7627.240074
62           2  gen_0_017  7639.748564

[86 rows x 3 columns]

In [10]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
    print(f"Genes:\n{i.genes}")
    print()

ID: gen_3_001
Score: 7186.7554717921885
Strategy count:
    U    D    N
1: 0    6    4    
2: 10   35   11   
3: 36   11   5    
4: 7    2    3    
Genes:
[[[0.56012192 0.06375045 0.01275009 0.36337754]
  [0.06177682 0.04811401 0.46911159 0.42099758]
  [0.20532187 0.05731524 0.37725543 0.36010746]
  [0.16751269 0.27918782 0.33502538 0.21827411]]

 [[0.22763636 0.30167566 0.17911992 0.29156807]
  [0.06319666 0.19130848 0.56876992 0.17672494]
  [0.32411608 0.31171149 0.00400189 0.36017054]
  [0.23048039 0.20359101 0.46396732 0.10196129]]

 [[0.21521217 0.01393114 0.39007206 0.38078463]
  [0.24012187 0.25886913 0.35287359 0.14813541]
  [0.27851334 0.4344808  0.13877409 0.14823177]
  [0.53172066 0.12511074 0.24151612 0.10165248]]]

ID: gen_2_001
Score: 7201.6712328288
Strategy count:
    U    D    N
1: 0    6    4    
2: 10   35   11   
3: 36   11   5    
4: 7    2    3    
Genes:
[[[0.4451504  0.08041299 0.0160826  0.45835402]
  [0.06177682 0.04811401 0.46911159 0.42099758]
  [0.19469163 