In [22]:
import os
import utils
import numpy as np
import pandas as pd

In [25]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        last_gen = sorted(map(lambda x: x.split("_"), 
                        os.listdir(f"{path}/individuals/")), 
                        key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
        print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
        last_gens.append(int(last_gen))
    return paths, last_gens

In [37]:
dir_path = "results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_29_19_31_36, last generation: 2


In [38]:
run = 0
gen = 2
path = dir_path + paths[run]

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [40]:
with open(dir_path + paths[run] + "/run_params.json", "r") as file:
    print(file.read())
    file.close()

{
    "objective": "deaths",
    "simulations": 3,
    "process": {
        "horizon": 74,
        "decision_period": 28,
        "policy": "weighted"
    },
    "population_size": 3,
    "random_individuals": true,
    "min_generations": 0
}


In [41]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
print("Strategy_count:")
print(f"{utils.tcolors.BOLD}{'#':<3} {'U':<5}{'D':<5}{'N':<5}{utils.tcolors.ENDC}")
for trend_count in range(3):
    strategy_count = individuals[0].strategy_count[gen]
    print(f"{trend_count+1:<2}| {strategy_count['U'][trend_count]:<5}{strategy_count['D'][trend_count]:<5}{strategy_count['N'][trend_count]:<5}")
print()
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {np.round(i.mean_score, 3)}")
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

Strategy_count:
#   U    D    N    
1 | 3    3    3    
2 | 2    2    3    
3 | 1    1    3    

1st place:
ID: gen_2_009
Score: 1548.548
Genes:
[[[0.16  0.186 0.194 0.262 0.198]
  [0.145 0.127 0.199 0.3   0.229]
  [0.097 0.316 0.26  0.07  0.258]]

 [[0.071 0.203 0.253 0.283 0.19 ]
  [0.228 0.175 0.256 0.19  0.151]
  [0.122 0.084 0.303 0.28  0.211]]

 [[0.099 0.304 0.231 0.245 0.121]
  [0.128 0.314 0.227 0.159 0.171]
  [0.232 0.146 0.2   0.165 0.256]]]

2nd place:
ID: gen_0_003
Score: 1569.005
Genes:
[[[0.    0.429 0.071 0.23  0.27 ]
  [0.029 0.072 0.197 0.476 0.226]
  [0.11  0.3   0.271 0.026 0.293]]

 [[0.227 0.162 0.239 0.291 0.081]
  [0.245 0.065 0.239 0.295 0.155]
  [0.033 0.107 0.346 0.283 0.232]]

 [[0.281 0.281 0.231 0.056 0.151]
  [0.276 0.164 0.22  0.185 0.155]
  [0.177 0.196 0.117 0.256 0.253]]]

3rd place:
ID: gen_0_001
Score: 1570.651
Genes:
[[[0.2   0.096 0.244 0.247 0.214]
  [0.148 0.142 0.161 0.284 0.265]
  [0.085 0.352 0.253 0.028 0.281]]

 [[0.    0.186 0.253 0.285 0.

In [30]:
print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.02772154 0.12981317 0.46594438 0.02156354 0.06452118 0.2904362 ]
  [0.45667618 0.         0.         0.12511083 0.         0.41821299]
  [0.         0.         0.99358962 0.         0.         0.00641038]]

 [[0.         0.         0.83418633 0.         0.         0.16581367]
  [0.23311384 0.2417248  0.31167746 0.         0.02920702 0.18427689]
  [0.01268598 0.         0.86100509 0.03305378 0.04611612 0.04713902]]

 [[0.14493941 0.43808816 0.27745665 0.         0.         0.13951578]
  [0.25355091 0.08738514 0.08570492 0.25355091 0.0047617  0.31504641]
  [0.01869097 0.15650874 0.20236493 0.0408563  0.5704409  0.01113814]]]

[0.12748654 0.11705778 0.44799215 0.05268171 0.07944966 0.17533217]
