In [182]:
import os
import utils
import numpy as np
import pandas as pd

In [183]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        try:
            last_gen = sorted(map(lambda x: x.split("_"), 
                            os.listdir(f"{path}/individuals/")), 
                            key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
            print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
            last_gens.append(int(last_gen))
        except:
            continue
    return paths, last_gens

In [184]:
dir_path = "results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_30_17_14_02, last generation: 11
Path: GA_2021_05_29_19_40_35, last generation: 21
Path: GA_2021_05_29_19_40_57, last generation: 21
Path: GA_2021_05_29_19_39_23, last generation: 21
Path: GA_2021_05_29_19_41_17, last generation: 21
Path: GA_2021_05_29_19_41_37, last generation: 21
Path: GA_2021_05_29_19_42_29, last generation: 21


In [200]:
run = 6
gen = 21
path = dir_path + paths[run]

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [201]:
with open(dir_path + paths[run] + "/run_params.json", "r") as file:
    print(file.read())
    file.close()

{
    "objective": "yll",
    "simulations": 20,
    "process": {
        "horizon": 74,
        "decision_period": 28,
        "policy": "weighted"
    },
    "population_size": 30,
    "random_individuals": true,
    "min_generations": 30
}


In [202]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
print("Strategy_count:")
print(f"{utils.tcolors.BOLD}{'#':<3} {'U':<5}{'D':<5}{'N':<5}{utils.tcolors.ENDC}")
for trend_count in range(3):
    strategy_count = individuals[0].strategy_count[gen]
    print(f"{trend_count+1:<2}| {strategy_count['U'][trend_count]:<5}{strategy_count['D'][trend_count]:<5}{strategy_count['N'][trend_count]:<5}")
print()
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {np.round(i.mean_score, 3)}")
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

Strategy_count:
#   U    D    N    
1 | 7    20   20   
2 | 1    20   20   
3 | 0    13   18   

1st place:
ID: gen_2_002
Score: 27286.4
Genes:
[[[0.421 0.222 0.154 0.176 0.027]
  [0.22  0.013 0.381 0.292 0.093]
  [0.066 0.066 0.401 0.112 0.356]]

 [[0.036 0.071 0.26  0.204 0.429]
  [0.175 0.213 0.347 0.022 0.243]
  [0.205 0.21  0.376 0.145 0.063]]

 [[0.049 0.082 0.346 0.302 0.22 ]
  [0.037 0.043 0.506 0.195 0.219]
  [0.243 0.035 0.273 0.435 0.013]]]

2nd place:
ID: gen_11_009
Score: 27360.45
Genes:
[[[0.363 0.223 0.133 0.132 0.149]
  [0.248 0.045 0.342 0.269 0.096]
  [0.07  0.16  0.329 0.105 0.336]]

 [[0.111 0.087 0.309 0.155 0.337]
  [0.235 0.228 0.307 0.025 0.206]
  [0.21  0.239 0.377 0.127 0.048]]

 [[0.105 0.081 0.332 0.291 0.191]
  [0.125 0.047 0.432 0.201 0.194]
  [0.239 0.043 0.268 0.386 0.063]]]

3rd place:
ID: gen_0_018
Score: 27383.9
Genes:
[[[0.273 0.    0.154 0.19  0.383]
  [0.03  0.205 0.155 0.3   0.31 ]
  [0.029 0.347 0.163 0.31  0.151]]

 [[0.357 0.269 0.231 0.11  0.0

In [203]:
print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.42081448 0.22171946 0.15384615 0.17647059 0.02714932]
  [0.22033898 0.01271186 0.38135593 0.29237288 0.09322034]
  [0.0657612  0.0657612  0.4011433  0.11179403 0.35554027]]

 [[0.03571429 0.07142857 0.26020408 0.20408163 0.42857143]
  [0.17537313 0.21268657 0.34701493 0.02238806 0.24253731]
  [0.20533398 0.21034212 0.37561093 0.14523623 0.06347674]]

 [[0.04945055 0.08241758 0.34615385 0.3021978  0.21978022]
  [0.03745487 0.0426444  0.50564079 0.19494585 0.21931408]
  [0.24290052 0.03542299 0.27326308 0.43519676 0.01321665]]]

[0.16146022 0.10612608 0.33824812 0.20940932 0.18475626]
