In [5]:
from covid import utils
import numpy as np
import pandas as pd

In [21]:
individuals_path =  "results/GA_20210508173938/individuals/individuals_2.pkl"
score_path =        "results/GA_20210508173938/final_scores/final_score_2.pkl"
overview_path =     "results/GA_20210508173938/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [23]:
overview.sort_values('mean_score')

generation     individual   mean_score
2           1  2157052449552  4047.619763
3           1  2157051561920  4128.644157
5           2  2157051729424  4469.259725
6           2  2157052449552  4482.051940
0           0  2157052449552  4574.034876
7           2  2157051561920  4596.778285
4           1  2157052450992  4899.601356
8           2  2157052450992  5342.060047
1           0  2157052450992  5532.106067

In [31]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count['U'][str(w)]:<5}{i.strategy_count['D'][str(w)]:<5}{i.strategy_count['N'][str(w)]:<5}")
    print(f"Genes\n{i.genes}")
    print()

ID: 2157051729424
Score: 4469.259725124631
Strategy count:
    U    D    N
1: 35   35   24   
2: 35   34   11   
3: 33   21   3    
4: 13   2    1    
Genes
[[[0.    1.    0.    0.   ]
  [0.    1.    0.    0.   ]
  [0.5   0.5   0.    0.   ]
  [0.5   0.5   0.    0.   ]]

 [[0.    1.    0.    0.   ]
  [0.    0.5   0.5   0.   ]
  [0.    0.75  0.    0.25 ]
  [0.    0.75  0.    0.25 ]]

 [[0.    1.    0.    0.   ]
  [0.5   0.5   0.    0.   ]
  [0.5   0.375 0.125 0.   ]
  [0.5   0.5   0.    0.   ]]]

ID: 2157052449552
Score: 4482.051939589164
Strategy count:
    U    D    N
1: 115  115  86   
2: 115  113  44   
3: 102  77   17   
4: 46   18   1    
Genes
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]]

ID: 2157051561920
Score: 4596.778284751467
Strategy count:
    U    D    N
1: 60   60   46   
2: 60   58   24   
3: 55   35   6    
4: 23   6   