In [29]:
import os
import utils
import numpy as np
import pandas as pd

In [30]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        try:
            last_gen = sorted(map(lambda x: x.split("_"), 
                            os.listdir(f"{path}/individuals/")), 
                            key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
            print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
            last_gens.append(int(last_gen))
        except:
            continue
    return paths, last_gens

In [31]:
dir_path = "results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_31_17_07_41, last generation: 38
Path: GA_2021_05_31_17_08_01, last generation: 38
Path: GA_2021_05_31_17_05_26, last generation: 34
Path: GA_2021_05_31_17_05_43, last generation: 38
Path: GA_2021_05_31_17_06_07, last generation: 40
Path: GA_2021_05_31_17_07_11, last generation: 34
Path: GA_2021_05_31_17_07_27, last generation: 37
Path: GA_2021_05_31_17_06_26, last generation: 42


In [75]:
run = -1
gen = 42
path = dir_path + paths[run]

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [76]:
with open(dir_path + paths[run] + "/run_params.json", "r") as file:
    print(file.read())
    file.close()

{
    "objective": "yll",
    "simulations": 15,
    "process": {
        "horizon": 74,
        "decision_period": 28,
        "policy": "weighted"
    },
    "population_size": 30,
    "random_individuals": false,
    "min_generations": 30
}


In [78]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
print("Strategy_count:")
print(f"{utils.tcolors.BOLD}{'#':<3} {'U':<5}{'D':<5}{'N':<5}{utils.tcolors.ENDC}")
for trend_count in range(7):
    strategy_count = individuals[0].strategy_count[gen]
    print(f"{trend_count+1:<2}| {strategy_count['U'][trend_count]:<5}{strategy_count['D'][trend_count]:<5}{strategy_count['N'][trend_count]:<5}")
print()
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {np.round(i.mean_score, 3)}")
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

Strategy_count:
#   U    D    N    
1 | 14   15   15   
2 | 6    13   15   
3 | 0    8    13   
4 | 0    0    11   
5 | 0    0    5    
6 | 0    0    0    
7 | 0    0    0    

1st place:
ID: gen_29_008
Score: 25877.4
Genes:
[[[0.001 0.013 0.969 0.016 0.001]
  [0.033 0.012 0.937 0.016 0.001]
  [0.002 0.003 0.737 0.259 0.   ]]

 [[0.001 0.002 0.984 0.013 0.001]
  [0.001 0.    0.982 0.015 0.002]
  [0.002 0.001 0.791 0.206 0.   ]]

 [[0.001 0.023 0.971 0.004 0.001]
  [0.002 0.002 0.977 0.018 0.001]
  [0.001 0.001 0.801 0.196 0.   ]]]

2nd place:
ID: gen_13_011
Score: 26633.533
Genes:
[[[0.037 0.049 0.82  0.047 0.046]
  [0.056 0.027 0.761 0.104 0.051]
  [0.076 0.107 0.752 0.065 0.   ]]

 [[0.019 0.038 0.826 0.027 0.09 ]
  [0.046 0.016 0.792 0.077 0.069]
  [0.088 0.045 0.812 0.055 0.   ]]

 [[0.043 0.026 0.859 0.043 0.029]
  [0.081 0.033 0.784 0.081 0.022]
  [0.06  0.062 0.78  0.098 0.   ]]]

3rd place:
ID: gen_41_010
Score: 26676.0
Genes:
[[[0.    0.035 0.923 0.024 0.018]
  [0.053 0.016 0.

In [74]:
print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.         0.0390625  0.6875     0.         0.2734375 ]
  [0.16839977 0.03278616 0.54985951 0.01704545 0.2319091 ]
  [0.         0.09114583 0.6875     0.         0.22135417]]

 [[0.         0.0390625  0.6875     0.         0.2734375 ]
  [0.         0.05552885 0.77295673 0.         0.17151442]
  [0.00735294 0.20404412 0.61580882 0.         0.17279412]]

 [[0.         0.05754389 0.88330433 0.         0.05915179]
  [0.         0.         0.74935897 0.         0.25064103]
  [0.         0.09583333 0.70625    0.         0.19791667]]]

[0.01952808 0.06833413 0.70444871 0.00189394 0.20579514]
