In [5]:
from covid import utils
import numpy as np
import pandas as pd

In [38]:
path = "results/GA_20210508182454"
gen = 0

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path =        f"{path}/final_scores/final_score_{gen}.pkl"
overview_path =     f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [39]:
overview.sort_values('mean_score')

generation     individual   mean_score
0           0  1809118761744  4574.034876
1           0  1809118763232  5532.106067

In [40]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count['U'][str(w)]:<5}{i.strategy_count['D'][str(w)]:<5}{i.strategy_count['N'][str(w)]:<5}")
    print(f"Genes\n{i.genes}")
    print()

ID: 1809118761744
Score: 4574.034875684036
Strategy count:
    U    D    N
1: 10   10   3    
2: 4    7    2    
3: 0    0    0    
4: 0    0    0    
Genes
[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]]

ID: 1809118763232
Score: 5532.106066670124
Strategy count:
    U    D    N
1: 10   10   3    
2: 4    7    2    
3: 0    0    0    
4: 0    0    0    
Genes
[[[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]]

