In [1]:
sys.path.append("..")
import os
import utils
import numpy as np
import pandas as pd

In [33]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    try: paths.remove('archive') 
    except: pass
    print(paths);print()
    for i in range(len(paths)):
        print(paths[i])
        path = dir_path + paths[i]
        gen = 0
        individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
        score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
        overview_path    =  f"{path}/generation_overview.csv"

        final_score = utils.read_pickle(score_path)
        individuals = utils.read_pickle(individuals_path)
        overview = pd.read_csv(overview_path)
        print(overview.sort_values('mean_score').head())
    return paths

In [34]:
dir_path = "../results/"
paths = read_all_results(dir_path)

['GA_2021_05_12_134133']

GA_2021_05_12_134133
   generation individual    mean_score
0           0  gen_0_003  29908.600000
1           0  gen_0_002  32823.633333
2           0  gen_0_001  47376.800000


In [30]:
path = dir_path + paths[0]
gen = 0

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

FileNotFoundError: [Errno 2] No such file or directory: '../results/GA_2021_05_11_161059/final_scores/final_score_0.pkl'

In [25]:
print(overview.sort_values('mean_score').head())


    generation individual    mean_score
19          10  gen_1_004  24208.186667
20          10  gen_2_003  24224.013333
21          10  gen_5_005  24240.453333
22          10  gen_0_004  24260.013333
23          10  gen_9_005  24276.800000


In [26]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
    print(f"Genes:\n{i.genes}")
    print()



ID: gen_0_004
Score: 29060.84
Strategy count:
    U    D    N
1: 58   69   22   
2: 8    12   0    
3: 1    1    0    
4: 0    0    0    
Genes:
[[[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]]

ID: gen_1_004
Score: 29062.133333333335
Strategy count:
    U    D    N
1: 58   69   22   
2: 8    12   0    
3: 1    1    0    
4: 0    0    0    
Genes:
[[[0.         0.         0.         1.        ]
  [0.         0.         0.5        0.5       ]
  [0.         0.27272727 0.27272727 0.45454545]
  [0.         0.         0.         1.        ]]

 [[0.         0.         0.375      0.625     ]
  [0.         0.         0.375      0.625     ]
  [0.375      0.         0.         0.625     ]
  [0.         0.         1.         0.        ]]

 [[0.         0.45454545 0.27272727 0.27272727]
  [0.         0.         0.5        0.5       ]
  [0.         0.4

In [86]:

print(individuals[0].genes)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print()
print(norm_genes)

[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]

[0.22171003 0.19816395 0.31566141 0.26446462]


In [91]:

print(individuals[0].genes)
genes = np.sum(individuals[0].genes, axis=(1))
print(genes)
norm = np.sum(genes, axis=1, keepdims=True)
print(norm)
norm_genes = np.divide(genes, norm)
print()
print(norm_genes)

[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]
[[0.67275943 0.72934127 1.33436396 1.26353534]
 [0.83639581 0.91828468 1.47761623 0.76770328]
 [1.15136508 0.7303414  0.97595671 1.1423368 ]]
[[4.]
 [4.]
 [4.]]

[[0.16818986 0.18233532 0.33359099 0.31588384]
 [0.20909895 0.22957117 0.36940406 0.19192582]
 [0.28784127 0.18258535 0.24398918 0.2855842 ]]
