In [10]:
sys.path.append("..")
import os
import utils
import numpy as np
import pandas as pd

In [101]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    try: paths.remove('archive') 
    except: pass
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        last_gen = sorted(map(lambda x: x.split("_"), 
                        os.listdir(f"{path}/individuals/")), 
                        key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
        print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
        last_gens.append(int(last_gen))
    return paths, last_gens

In [102]:
dir_path = "../results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_12_180608, last generation: 19
Path: GA_2021_05_12_180637, last generation: 19
Path: GA_2021_05_12_180650, last generation: 18
Path: GA_2021_05_12_180545, last generation: 20
Path: GA_2021_05_12_180556, last generation: 19
Path: GA_2021_05_12_180700, last generation: 20


In [139]:
run = 1
path = dir_path + paths[run]
gen = 19

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [140]:
with open(dir_path + paths[run] + "/run_info.txt", "r") as file:
    print(file.read())
    file.close()

Time: 12.05.2021 (18:06:37)
Objective: deaths
Number of simulations: 30
MDP params: (Horizon: 79, Decision period: 28, Policy: weighted, )
Initial population size: 20
Random individual genes: True
Minimum number of generations: 20


In [142]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    if ix == 0:
        print("Strategy count:")
        print(f"{'U':>5}{'D':>5}{'N':>5}")
        for w in range(1,4):
            print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
        print()
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

Strategy count:
    U    D    N
1: 45   41   19   
2: 35   16   3    
3: 9    2    0    
1st place:
ID: gen_16_012
Score: 1722.108597652021
Genes:
[[[0.118 0.023 0.166 0.692]
  [0.537 0.171 0.109 0.183]
  [0.117 0.339 0.056 0.489]]

 [[0.214 0.302 0.315 0.17 ]
  [0.189 0.24  0.264 0.307]
  [0.355 0.    0.179 0.466]]

 [[0.269 0.325 0.282 0.123]
  [0.249 0.094 0.254 0.404]
  [0.224 0.252 0.353 0.171]]]

2nd place:
ID: gen_8_003
Score: 1732.9542564724231
Genes:
[[[0.371 0.02  0.087 0.521]
  [0.448 0.303 0.1   0.149]
  [0.122 0.348 0.224 0.307]]

 [[0.298 0.336 0.207 0.16 ]
  [0.155 0.121 0.325 0.399]
  [0.294 0.057 0.206 0.443]]

 [[0.252 0.071 0.438 0.239]
  [0.347 0.134 0.321 0.198]
  [0.381 0.179 0.261 0.179]]]

3rd place:
ID: gen_0_006
Score: 1736.4754949624482
Genes:
[[[0.43  0.022 0.045 0.503]
  [0.537 0.171 0.109 0.183]
  [0.117 0.339 0.056 0.489]]

 [[0.061 0.443 0.316 0.179]
  [0.164 0.092 0.344 0.4  ]
  [0.208 0.    0.434 0.358]]

 [[0.232 0.037 0.5   0.232]
  [0.249 0.094 0.25

In [116]:

print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.11835709 0.02293166 0.16633865 0.69237261]
  [0.53714286 0.17142857 0.10857143 0.18285714]
  [0.11666667 0.33888889 0.05555556 0.48888889]]

 [[0.21373949 0.30158984 0.31515082 0.16951985]
  [0.18883638 0.23997115 0.26393031 0.30726215]
  [0.35502232 0.         0.17886786 0.46610982]]

 [[0.2689749  0.32542643 0.2824441  0.12315457]
  [0.24882629 0.09389671 0.25352113 0.40375587]
  [0.22363831 0.25164827 0.35337842 0.17133499]]]

[0.25235603 0.19397572 0.21975092 0.33391732]


In [91]:

print(individuals[0].genes)
genes = np.sum(individuals[0].genes, axis=(1))
print(genes)
norm = np.sum(genes, axis=1, keepdims=True)
print(norm)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]
[[0.67275943 0.72934127 1.33436396 1.26353534]
 [0.83639581 0.91828468 1.47761623 0.76770328]
 [1.15136508 0.7303414  0.97595671 1.1423368 ]]
[[4.]
 [4.]
 [4.]]

[[0.16818986 0.18233532 0.33359099 0.31588384]
 [0.20909895 0.22957117 0.36940406 0.19192582]
 [0.28784127 0.18258535 0.24398918 0.2855842 ]]
