In [2]:
sys.path.append("..")
import os
import utils
import numpy as np
import pandas as pd

In [66]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    try: paths.remove('archive') 
    except: pass
    print(paths);print()
    for i in range(len(paths)):
        print(paths[i])
        path = dir_path + paths[i]
        gen = 0
        individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
        score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
        overview_path    =  f"{path}/generation_overview.csv"

        final_score = utils.read_pickle(score_path)
        individuals = utils.read_pickle(individuals_path)
        overview = pd.read_csv(overview_path)
        print(overview.sort_values('mean_score').head())

In [67]:
dir_path = "../results/"
read_all_results(dir_path)

['GA_2021_05_10_224057', 'GA_2021_05_10_13:48:00', 'GA_2021_05_10_13:47:48', 'GA_2021_05_10_224114', 'GA_2021_05_10_13:47:08', 'GA_2021_05_10_224011', 'GA_2021_05_10_224044', 'GA_2021_05_10_224026', 'GA_2021_05_10_13:46:17', 'GA_2021_05_10_13:46:34']

GA_2021_05_10_224057
     generation  individual    mean_score
345          10   gen_0_022  43479.866667
346          10   gen_7_005  43650.733333
347          10  gen_10_001  43833.866667
348          10   gen_0_005  43836.833333
349          10   gen_3_001  43836.833333
GA_2021_05_10_13:48:00
     generation individual   mean_score
161           7  gen_7_004  7037.229110
162           7  gen_6_002  7037.346879
163           7  gen_5_002  7041.395323
164           7  gen_4_005  7047.574008
165           7  gen_2_003  7048.257906
GA_2021_05_10_13:47:48
    generation individual    mean_score
86           4  gen_4_003  47555.186667
87           4  gen_2_005  47580.706667
88           4  gen_3_004  47620.386667
89           4  gen_0_010  47

In [83]:
path = dir_path + 'GA_2021_05_10_224044'
gen = 0

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [84]:
print(overview.sort_values('mean_score').head())


     generation individual   mean_score
126           4  gen_0_016  3230.839609
127           4  gen_4_003  3241.485608
128           4  gen_3_005  3269.295838
129           4  gen_0_007  3281.756216
130           4  gen_0_025  3300.032463


In [85]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
    print(f"Genes:\n{i.genes}")
    print()



ID: gen_0_008
Score: 3862.5981318452596
Strategy count:
    U    D    N
1: 0    0    0    
2: 0    29   0    
3: 25   11   0    
4: 4    0    0    
Genes:
[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]

ID: gen_0_012
Score: 3900.225257130464
Strategy count:
    U    D    N
1: 0    0    0    
2: 0    29   0    
3: 25   11   0    
4: 4    0    0    
Genes:
[[[0.33220339 0.25423729 0.24745763 0.16610169]
  [0.09444444 0.18333333 0.21111111 0.51111111]
  [0.0321100

In [86]:

print(individuals[0].genes)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print()
print(norm_genes)

[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]

[0.22171003 0.19816395 0.31566141 0.26446462]


In [91]:

print(individuals[0].genes)
genes = np.sum(individuals[0].genes, axis=(1))
print(genes)
norm = np.sum(genes, axis=1, keepdims=True)
print(norm)
norm_genes = np.divide(genes, norm)
print()
print(norm_genes)

[[[0.33793103 0.42758621 0.10344828 0.13103448]
  [0.02884615 0.04807692 0.41346154 0.50961538]
  [0.12612613 0.04504505 0.5045045  0.32432432]
  [0.17985612 0.20863309 0.31294964 0.29856115]]

 [[0.26223776 0.23776224 0.32517483 0.17482517]
  [0.07909605 0.14124294 0.49717514 0.28248588]
  [0.29083665 0.09561753 0.36653386 0.24701195]
  [0.20422535 0.44366197 0.28873239 0.06338028]]

 [[0.51075269 0.01075269 0.28494624 0.19354839]
  [0.20408163 0.33673469 0.20748299 0.25170068]
  [0.30970149 0.24626866 0.09328358 0.35074627]
  [0.12682927 0.13658537 0.3902439  0.34634146]]]
[[0.67275943 0.72934127 1.33436396 1.26353534]
 [0.83639581 0.91828468 1.47761623 0.76770328]
 [1.15136508 0.7303414  0.97595671 1.1423368 ]]
[[4.]
 [4.]
 [4.]]

[[0.16818986 0.18233532 0.33359099 0.31588384]
 [0.20909895 0.22957117 0.36940406 0.19192582]
 [0.28784127 0.18258535 0.24398918 0.2855842 ]]
