In [2]:
sys.path.append("..")
import utils
import numpy as np
import pandas as pd

In [3]:
path = "../results/GA_2021_05_10_222237"
gen = 0

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [5]:
overview.sort_values('mean_score').head()

generation individual   mean_score
0           0  gen_0_012  7370.941255
1           0  gen_0_020  7376.338298
2           0  gen_0_026  7390.790092
3           0  gen_0_027  7393.806147
4           0  gen_0_022  7399.727197

In [6]:
for i in sorted(individuals, key=lambda x: x.mean_score):
    print(f"ID: {i.ID}")
    print(f"Score: {i.mean_score}")
    print("Strategy count:")
    print(f"{'U':>5}{'D':>5}{'N':>5}")
    for w in range(1,5):
        print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
    print(f"Genes:\n{i.genes}")
    print()

3 ]
  [0.23255814 0.40465116 0.2        0.1627907 ]
  [0.35795455 0.26704545 0.22727273 0.14772727]]]

ID: gen_0_027
Score: 7393.806146529221
Strategy count:
    U    D    N
1: 0    0    60   
2: 0    0    60   
3: 60   60   60   
4: 727214772621577
Genes:
[[[0.26363636 0.17727273 0.35       0.20909091]
  [0.1920904  0.10169492 0.36723164 0.33898305]
  [0.41803279 0.10655738 0.13114754 0.3442623 ]
  [0.14893617 0.26808511 0.18297872 0.4       ]]

 [[0.07655502 0.28229665 0.22009569 0.42105263]
  [0.23048327 0.26394052 0.29739777 0.20817844]
  [0.46666667 0.23333333 0.16111111 0.13888889]
  [0.36111111 0.18981481 0.06018519 0.38888889]]

 [[0.12554113 0.32467532 0.14285714 0.40692641]
  [0.12       0.44666667 0.26666667 0.16666667]
  [0.01724138 0.56896552 0.31034483 0.10344828]
  [0.04368932 0.38349515 0.22815534 0.34466019]]]

ID: gen_0_022
Score: 7399.727197163962
Strategy count:
    U    D    N
1: 0    0    60   
2: 0    0    60   
3: 60   60   60   
4: 679664447120182
Genes:
[[[0.1