In [55]:
sys.path.append("..")
import os
import utils
import numpy as np
import pandas as pd

In [58]:
def read_all_results(dir_path):
    paths = os.listdir(dir_path)
    try: paths.remove('archive') 
    except: pass
    last_gens = []
    for i in range(len(paths)):
        path = dir_path + paths[i]
        last_gen = sorted(map(lambda x: x.split("_"), 
                        os.listdir(f"{path}/individuals/")), 
                        key=lambda x: int(x[1].split(".")[0]))[-1][-1][:-4]
        print(f"Path: {paths[i]}, last generation: {int(last_gen)}")
        last_gens.append(int(last_gen))
    return paths, last_gens

In [59]:
dir_path = "../results/"
paths, last_gens = read_all_results(dir_path)

Path: GA_2021_05_14_13_38_13, last generation: 31
Path: GA_2021_05_14_13_37_09, last generation: 29
Path: GA_2021_05_14_13_39_01, last generation: 29
Path: GA_2021_05_14_13_37_48, last generation: 31
Path: GA_2021_05_14_13_38_36, last generation: 32
Path: GA_2021_05_14_13_37_33, last generation: 31


In [89]:
run = 4
gen = 32
path = dir_path + paths[run]

individuals_path =  f"{path}/individuals/individuals_{gen}.pkl"
score_path       =  f"{path}/final_scores/final_score_{gen}.pkl"
overview_path    =  f"{path}/generation_overview.csv"

final_score = utils.read_pickle(score_path)
individuals = utils.read_pickle(individuals_path)
overview = pd.read_csv(overview_path)

In [90]:
with open(dir_path + paths[run] + "/run_params.json", "r") as file:
    print(file.read())
    file.close()

{
    "objective": "weighted",
    "simulations": 20,
    "process": {
        "horizon": 79,
        "decision_period": 28,
        "policy": "weighted"
    },
    "population_size": 40,
    "random_individuals": true,
    "min_generations": 40
}


In [91]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n//10%10!=1)*(n%10<4)*n%10::4])
for ix, i in enumerate(sorted(individuals, key=lambda x: x.mean_score)):
    if ix == 0:
        print("Strategy count:")
        print(f"{'U':>5}{'D':>5}{'N':>5}")
        for w in range(1,4):
            print(f"{w}: {i.strategy_count[gen]['U'][w]:<5}{i.strategy_count[gen]['D'][w]:<5}{i.strategy_count[gen]['N'][w]:<5}")
        print()
    print(f"{utils.tcolors.BOLD}{ordinal(ix+1)} place:{utils.tcolors.ENDC}")
    print(f"ID: {i.ID}")
    print(f"Score: {np.round(i.mean_score, 3)}")
    
    print(f"Genes:\n{np.round(i.genes, 3)}")
    print()

Strategy count:
    U    D    N
1: 19   20   8    
2: 12   18   2    
3: 1    5    0    

1st place:
ID: gen_26_005
Score: 6862.496
Genes:
[[[0.034 0.    0.545 0.421 0.    0.   ]
  [0.003 0.414 0.332 0.089 0.058 0.104]
  [0.    0.    0.286 0.714 0.    0.   ]]

 [[0.06  0.012 0.076 0.763 0.    0.089]
  [0.229 0.064 0.134 0.459 0.    0.115]
  [0.09  0.    0.09  0.    0.    0.82 ]]

 [[0.044 0.177 0.238 0.    0.541 0.   ]
  [0.483 0.405 0.    0.    0.098 0.014]
  [0.37  0.    0.52  0.    0.035 0.075]]]

2nd place:
ID: gen_27_002
Score: 6870.334
Genes:
[[[0.099 0.    0.436 0.465 0.    0.   ]
  [0.003 0.414 0.332 0.089 0.058 0.104]
  [0.    0.    0.286 0.714 0.    0.   ]]

 [[0.    0.    0.    0.895 0.    0.105]
  [0.264 0.073 0.    0.529 0.    0.133]
  [0.09  0.    0.09  0.    0.    0.82 ]]

 [[0.011 0.415 0.171 0.08  0.323 0.   ]
  [0.483 0.405 0.    0.    0.098 0.014]
  [0.37  0.    0.52  0.    0.035 0.075]]]

3rd place:
ID: gen_28_011
Score: 6870.421
Genes:
[[[0.025 0.    0.55  0.425 0.

In [26]:
print(individuals[0].genes, end="\n"*2)
genes = np.sum(individuals[0].genes, axis=(0,1))
norm = np.sum(genes)
norm_genes = np.divide(genes, norm)
print(norm_genes)

[[[0.08571429 0.         0.05714286 0.85714286]
  [0.         0.         0.37860804 0.62139196]
  [0.1119403  0.         0.         0.8880597 ]]

 [[0.         0.05666848 0.5984192  0.34491232]
  [0.         0.25       0.0625     0.6875    ]
  [0.         0.         0.         1.        ]]

 [[0.11842008 0.         0.54769288 0.33388704]
  [0.02637035 0.         0.18581543 0.78781422]
  [0.11864407 0.         0.25       0.63135593]]]

[0.05123212 0.03407428 0.23113093 0.68356267]
